apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  tolerations:
   
   - key: virtual-kubelet.io/provider
     operator: Equal
     value: k8sgpu
     effect: NoExecute
    
  
   - key: virtual-node.interlink/no-schedule
     operator: Exists
    
     effect: NoSchedule 
     
   - key: node.kubernetes.io/network-unavailable
     operator: Exists
     effect: NoSchedule
     
   - key: node.kubernetes.io/not-ready
     operator: Exists
     effect: NoSchedule
    
   
     
    
       
