apiVersion: v1
kind: Service
metadata:
  name: databuff
  labels:
    app: databuff
spec:
  ports:
  - name: ginport
    port: 8080
    
  clusterIP: None
  
  selector:
    app: databuff
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: databuff
spec:
  serviceName: databuff
  replicas: 1
  selector:
    matchLabels:
      app: databuff
  template:
    metadata:
      labels:
        app: databuff
    spec:
      containers:
      - name: databuff
        image: romanoa77/databuff:alpha.k8s
        #command: ["sleep","infinity"]
        ports:
        - containerPort: 8080
          name: ginport
        volumeMounts:
         - name: adata
           mountPath: /app/appdata
         - name: gdata 
           mountPath: /app/data 

      volumes:
      - name: adata
        persistentVolumeClaim:
         claimName: adm
      - name: gdata  
        persistentVolumeClaim:
          claimName: gwdata 

  
      
        
