apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gwdata
spec:
 accessModes: [ "ReadWriteMany" ]
 storageClassName: standard
 resources:
  requests:
   storage: 1M
 storageClassName: standard