apiVersion: v1
kind: Service
metadata:
  name: dslogic
  labels:
    app: dslogic
spec:
  ports:
  - name: dsport
    port: 5000
    
  
  
  selector:
    app: dslogic
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dslog-deploy
  labels:
    app: dslogic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dslogic
  template:
    metadata:
      labels:
        app: dslogic
    spec:
      containers:
       - name: dslogic
         image: romanoa77/dslogic:alpha.k8s.0
         ports:
         - containerPort: 5000