apiVersion: v1
kind: PersistentVolume
metadata:
  name: admpv
  labels:
   type: local
spec:
  capacity:
   storage: "1Mi"
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
   path: "/mnt/adata"
  