apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwpv
  labels:
   type: local
spec:
  capacity:
   storage: "1Mi"
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
   path: "/mnt/gwdata"
  